FROM node:22 AS build
WORKDIR /app
COPY package.json .
RUN npm install
COPY . .
RUN npm run build

FROM nginx:alpine
ENV OPENAI_API_KEY=undefined
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
